export const ISSUE_REQUEST = 'ISSUE_REQUEST';
export const ISSUE_FETCH = 'ISSUE_FETCH';
export const ISSUE_FETCH_FAILURE = 'ISSUE_FETCH_FAILURE';
export const ISSUE_CLEAR = 'ISSUE_CLEAR';

export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_FETCH = 'ADD_COMMENT_FETCH';
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE';

export const ISSUE_USERS_REQUEST = 'ISSUE_USERS_REQUEST';
export const ISSUE_USERS_FETCH = 'ISSUE_USERS_FETCH';
export const ISSUE_USERS_FAILURE = 'ISSUE_USERS_FAILURE';

export const ISSUE_UPDATE_REQUEST = 'ISSUE_UPDATE_REQUEST';
export const ISSUE_UPDATE_FETCH = 'ISSUE_UPDATE_FETCH';
export const ISSUE_UPDATE_FAILURE = 'ISSUE_UPDATE_FAILURE';
export const ISSUE_UPDATE_USER = 'ISSUE_UPDATE_USER';

export const ISSUE_UPDATE_DESCRIPTION = 'ISSUE_UPDATE_DESCRIPTION';
export const ISSUE_UPDATE_SUMMARY = 'ISSUE_UPDATE_SUMMARY';
export const ISSUE_UPDATE_PRIORITY = 'ISSUE_UPDATE_PRIORITY';
export const ISSUE_UPDATE_STATUS = 'ISSUE_UPDATE_STATUS';
