export const ISSUE_REQUEST = 'ISSUE_REQUEST';
export const ISSUE_FETCH = 'ISSUE_FETCH';
export const ISSUE_FETCH_FAILURE = 'ISSUE_FETCH_FAILURE';

export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_FETCH = 'ADD_COMMENT_FETCH';
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE';
