/*
 * action types
 */

export const PROJECT_LIST_REQUEST = 'PROJECT_LIST_REQUEST';
export const PROJECT_LIST_FETCH = 'PROJECT_LIST_FETCH';
export const PROJECT_LIST_FAILURE = 'PROJECT_LIST_FAILURE';

export const PROJECT_CONFIG_REQUEST = 'PROJECT_CONFIG_REQUEST';
export const PROJECT_CONFIG_FETCH = 'PROJECT_CONFIG_FETCH';
export const PROJECT_CONFIG_FAILURE = 'PROJECT_CONFIG_FAILURE';

export const PROJECT_USERS_REQUEST = 'PROJECT_USERS_REQUEST';
export const PROJECT_USERS_FETCH = 'PROJECT_USERS_FETCH';
export const PROJECT_USERS_FAILURE = 'PROJECT_USERS_FAILURE';

export const PROJECT_PRIORITIES_REQUEST = 'PROJECT_PRIORITIES_REQUEST';
export const PROJECT_PRIORITIES_FETCH = 'PROJECT_PRIORITIES_FETCH';
export const PROJECT_PRIORITIES_FAILURE = 'PROJECT_PRIORITIES_FAILURE';

export const PROJECT_CLEAR = 'PROJECT_CLEAR';
export const PROJECT_SELECTED = 'PROJECT_SELECTED';
