/*
 * action types
 */

export const SPRINTS_LIST_REQUEST = 'SPRINTS_LIST_REQUEST';
export const SPRINTS_LIST_FETCH = 'SPRINTS_LIST_FETCH';
export const SPRINTS_LIST_FAILURE = 'SPRINTS_LIST_FAILURE';

export const SPRINT_ISSUES_REQUEST = 'SPRINT_ISSUES_REQUEST';
export const SPRINT_ISSUES_FETCH = 'SPRINT_ISSUES_FETCH';
export const SPRINT_ISSUES_FAILURE = 'SPRINT_ISSUES_FAILURE';

export const SPRINT_REQUEST = 'SPRINT_REQUEST';
export const SPRINT_FETCH = 'SPRINT_FETCH';
export const SPRINT_FAILURE = 'SPRINT_FAILURE';