/*
 * action types
 */

export const SPRINTS_LIST_REQUEST = 'SPRINTS_LIST_REQUEST';
export const SPRINTS_LIST_FETCH = 'SPRINTS_LIST_FETCH';
export const SPRINTS_LIST_FAILURE = 'SPRINTS_LIST_FAILURE';

export const SPRINT_ISSUES_REQUEST = 'SPRINT_ISSUES_REQUEST';
export const SPRINT_ISSUES_FETCH = 'SPRINT_ISSUES_FETCH';
export const SPRINT_ISSUES_FAILURE = 'SPRINT_ISSUES_FAILURE';

export const SPRINT_REQUEST = 'SPRINT_REQUEST';
export const SPRINT_FETCH = 'SPRINT_FETCH';
export const SPRINT_FAILURE = 'SPRINT_FAILURE';
export const SPRINT_UPDATE_POINTS = 'SPRINT_UPDATE_POINTS';

export const BURNDOWN_REQUEST = 'BURNDOWN_REQUEST';
export const BURNDOWN_FETCH = 'BURNDOWN_FETCH';
export const BURNDOWN_FETCH_FAILURE = 'BURNDOWN_FETCH_FAILURE';

export const VELOCITY_REQUEST = 'VELOCITY_REQUEST';
export const VELOCITY_FETCH = 'VELOCITY_FETCH';
export const VELOCITY_FETCH_FAILURE = 'VELOCITY_FETCH_FAILURE';


export const REPORT_REQUEST = 'REPORT_REQUEST';
export const REPORT_FETCH = 'REPORT_FETCH';
export const REPORT_FETCH_FAILURE = 'REPORT_FETCH_FAILURE';
